" user strict";
let
a1=[5, "truc", true],
a2= new Array(5,"truc", true);
console.log(a1,a2);
console.log(a1[1]);
console.log(a1.length);
console.log(a1[a1.length-1]);
console.log(a1.at(-1));
console.log("salut".at(-1), "salut"[2]);
a1.push("bidule");
console.log(a1);
a1.pop();
console.log(a1);
a1.shift();
console.log(a1);
a1.unshift(42);
console.log(a1);
a1.splice(1);
console.log(a1);
a2.splice(1,1);
console.log(a2);
a2.push(1, 2, 3, 4);
console.log(a2);
a2.splice(1,1, "chaussette","banane");
console.log(a2);
a2.splice(2,0,"cerise");
console.log(a2);
let a3=[4,1,12,42,8,14];
a3.sort();
console.log(a3);
a1[8]="pomme";
console.log(a1);
a2[a2.length]="pomme";
console.log(a2);
let a4=a2;
console.log(a4);
a4[0]="saperlipopette";
console.log(a4,a2);
console.log(a2,...a2);
let a5= ["pizza", ...a4, "pomme","banane"]
console.log(a5);
let a6=["pizza",a4,"pomme","banane"]
console.log(a6);
console.log(a6[1][3]);
let a7=[[[[[["coucou"]]]]]];
console.log(a7, a7[0], [0],[0],[0],[0],[0]);
let tmp=a6[0];
a6[0]=a6[3];
a6[3]=tmp;
console.log(a3);
console.log(a3);
[a3[0],a3[1]]=[a3[1],a3[0]];
console.log("a3",a3);
let o1= {nom: "dupont", age:45, loisir:["bowling","mahjong"]};
console.log(o1);
console.log(o1,o1["nom"], o1 ["age"], o1["loisir"]);
console.log(o1.nom, o1.age, o1.loisir);
let v = "age";
console.log(o1[v],o1.v);
console.log(o1.loisir[0], o1["loisir"][0]);
let o2={vegetal: {legume:{haricot:{couleur:"vert"}}}};
console.log(o2.vegetal.legume.haricot.couleur);
let o3=o1;
o3.signe="balance";
console.log(o1,o3);
let o4={...o1};
o4.signe="scorpion";
console.log(o1,o4)
console.log (a1,{...a1});
o4.yeux = "vert";
let o5={...o4,...o1};
console.log(o5);
const a0=[],o0={};
a0[0]="coucou";
o0.text="coucou";
console.log(a0,o0);
let b1=true, b2=false;
console.log("1<2:",1<2);
console.log("1>2:",1>2);
console.log("1<=2:",1<=2);
console.log("1>=2:",1>=2);
console.log("1==1:",1==1);
console.log("1==`1`:",1==`1`);
console.log("1===1:",1===1);
console.log("1==`=`1`:",1===`1`);
console.log("1!=1:",1!=1);
console.log("1!==1`:",1!==`1`);
console.log("b1:",b1,"b2:",b2);
console.log("!b1:",!b1,"!b2:",!b2);
console.log(true&&true,true&&false,false&&true,false&&false);
console.log(true||true,true||false,false||true,false||false);
console.log(true&&[false||true]);
let nb=0;
console.log(true&&++nb,nb);
console.log(false&&++nb,nb);
console.log(false||++nb,nb);
console.log(true||++nb,nb);


